apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: adaptive-quality
type: Opaque
stringData:
  POSTGRES_USER:     "aqp"
  POSTGRES_PASSWORD: "aqp_secret"
  GRAFANA_PASSWORD:  "admin"
  MLFLOW_BACKEND_STORE_URI: <base64 of "postgresql://user:pass@postgres:5432/mlflow">