apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: adaptive-quality
type: Opaque
stringData:
  POSTGRES_USER:     "aqp"
  POSTGRES_PASSWORD: "aqp_secret"
  GRAFANA_PASSWORD:  "admin"